#!/bin/sh

source=$1
if [ -z "$1" ]; then
    source="base.html"
fi

target=$2
if [ -z "$1" ]; then
    target="out.html"
fi

cp "$source" "$target"

while (grep -q "{{\s*..*\s*}}" $target); do
    templater_pass $target > temp
    cat temp > $target
done

rm temp
cat $target
