#!/bin/sh

awk '

/{{\s*..*\.html\s*[0-9][0-9]*\s*}}/{
    for (i=0; i<$3; i++) {
        while((getline line < $2) > 0 ){print "\t",line};
        close($2);
    };
    next;
}

/{{\s*..*\.html\s*}}/{
	while((getline line < $2) > 0 ){print "\t",line};
	close($2);
	next;
}

{print $0}' $1

#/{{  *..*\.hml ..*  *}}/{
#while (("ls /$3" | getline line) > 0) {
#    while(( getline line2 < line) > 0 ) {
#        print "\t",line2
#    };
#    close(line);
#};
#}
#
#/{{  *..*\.html ..*\.txt  *}}/{
#	while((getline line < $3) > 0 ){
#		while((getline line2 < line) > 0 ){print "\t",line2};
#		close(line);
#    };
#	close($3);
#    next;
#}


